# Build customization
builds:
  - main: ./cmd/kvmtop
    binary: kvmtop
    goos:
      - linux
    goarch:
      - amd64

nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  vendor: Christopher B. Hauser
  homepage: https://cha87de.github.io/kvmtop/
  maintainer: Christopher B. Hauser <post@c-ha.de>
  description: Monitor virtual machine experience from outside on KVM hypervisor level
  license: GPL-3.0

  # Formats to be generated.
  formats:
    - deb
    - rpm

  # Override default /usr/local/bin destination for binaries
  bindir: /usr/bin

  # additional files, e.g. systemd service
  files:
    "pkgbuild/kvmtop.service": "/etc/systemd/system/kvmtop.service"
  config_files:
    "pkgbuild/kvmtop.conf": "/etc/kvmtop.conf"

dockers:
  -
    goos: linux
    goarch: amd64
    goarm: ''
    binary: kvmtop
    image_templates:
    - 'cha87de/kvmtop:{{ .Tag }}'
    - 'cha87de/kvmtop:latest'
