language: go
go:
  - '1.9' 

services:
  - docker

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvirt-dev rpm

install:
  - "go get -d -v ./..."
  - "go install ./..."
  - "cp $GOPATH/bin/kvmtop ."

before_deploy:
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    skip_cleanup: true
    script: docker build -t cha87de/kvmtop:master . ; docker push cha87de/kvmtop:master 
    on:
      branch: master
  - provider: script
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
